import 'bootstrap/dist/css/bootstrap.css';
import "./globals.css";
import Navbar from "./Components/Navbar";
import Script from 'next/script';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='remove-typing-cursor'>
        <Navbar />
        {children}
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></Script>
      </body>
    </html>
  );
}
